// The cuisine vocabulary the app understands. Kept deliberately broad so taste preferences
// can be specific. These labels are produced server-side from Google place types (see
// supabase/functions/places-proxy: TYPE_TO_CUISINE) and refined by first-party tags.
//
// "Bubble Tea" has no Google place type; it is a manual category (a handful of Sydney chains
// tagged by hand as first-party data), kept here so it is selectable in preferences.
export const CUISINES: string[] = [
  "Afghan",
  "African",
  "American",
  "Asian",
  "BBQ",
  "Bakery",
  "Bar",
  "Breakfast",
  "Brazilian",
  "Brunch",
  "Bubble Tea",
  "Burgers",
  "Cafe",
  "Chinese",
  "Deli",
  "Dessert",
  "Fast Food",
  "Fine Dining",
  "French",
  "Greek",
  "Ice Cream",
  "Indian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Juice",
  "Korean",
  "Lebanese",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Pizza",
  "Pub",
  "Ramen",
  "Sandwiches",
  "Seafood",
  "Spanish",
  "Steakhouse",
  "Sushi",
  "Tea",
  "Thai",
  "Turkish",
  "Vegan",
  "Vegetarian",
  "Vietnamese",
  "Wine Bar",
];
