// Languages offered in onboarding. A light, non-sensitive proxy for food heritage (it replaced
// the original "ethnicity" question). Ordered roughly by global speaker count, then alphabetical.
export const LANGUAGES: string[] = [
  "English",
  "Mandarin",
  "Cantonese",
  "Hindi",
  "Spanish",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Thai",
  "French",
  "German",
  "Italian",
  "Greek",
  "Turkish",
  "Persian",
  "Indonesian",
  "Malay",
  "Filipino",
  "Tamil",
  "Punjabi",
  "Urdu",
  "Hebrew",
  "Polish",
  "Ukrainian",
];
